name: neural_net_experiments
description: Simple dart library to learn about creating neural net-like data structures with dart code
version: 0.0.3
homepage: https://github.com/kevinvandenbreemen/dartCellsAndNeuralNets
author: Kevin VanDenBreemen <kevin.vandenbreemen@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  linalg: ^0.3.2
  gviz: ^0.3.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
